/**
 * Landing page actions
 */
export const SET_PAIRS = 'SET_PAIRS';
export const PAIRS_REQUEST = 'PAIRS_REQUEST';
export const PAIRS_RESPONSE = 'PAIRS_RESPONSE';
export const RESOURCE_ERROR = 'RESOURCE_ERROR';

/**
 * Swap actions
 */
export const COMPLETE_SWAP = 'COMPLETE_SWAP';
export const INIT_SWAP = 'INIT_SWAP';
export const SET_SWAP_INVOICE = 'SET_SWAP_INVOICE';
export const SET_SWAP_STATUS = 'SET_SWAP_STATUS';
export const SWAP_REQUEST = 'SWAP_REQUEST';
export const SWAP_RESPONSE = 'SWAP_RESPONSE';

/**
 * Reverse Swap actions
 */
export const COMPLETE_REVERSE_SWAP = 'COMPLETE_REVERSE_SWAP';
export const INIT_REVERSE_SWAP = 'INIT_REVERSE_SWAP';
export const SET_REVERSE_SWAP_ADDRESS = 'SET_REVERSE_SWAP_ADDRESS';
export const SET_REVERSE_SWAP_STATUS = 'SET_REVERSE_SWAP_STATUS';
export const SET_IS_RECONNECTING = 'SET_IS_RECONNECTING';
export const REVERSE_SWAP_REQUEST = 'REVERSE_SWAP_REQUEST';
export const REVERSE_SWAP_RESPONSE = 'REVERSE_SWAP_RESPONSE';

/**
 * Refund actions
 */
export const COMPLETE_REFUND = 'COMPLETE_REFUND';
export const SET_REFUND_FILE = 'SET_REFUND_FILE';
export const SET_REFUND_TXHASH = 'SET_REFUND_TXHASH';
export const SET_REFUND_DESTINATION = 'SET_REFUND_DESTINATION';
export const SET_REFUND_TRANSACTION_HASH = 'SET_REFUND_TRANSACTION_HASH';
export const REFUND_REQUEST = 'REFUND_REQUEST';
export const REFUND_RESPONSE = 'REFUND_RESPONSE';
