/**
 * Global actions
 */
export const NAVIGATE = 'NAVIGATE';
export const NEW_KEYS = 'NEW_KEYS';

/**
 * Swap actions
 */
export const COMPLETE_SWAP = 'COMPLETE_SWAP';
export const SET_SWAP_AMOUNT = 'SET_SWAP_AMOUNT';
export const SET_SWAP_INVOICE = 'SET_SWAP_INVOICE';
export const SWAP_REQUEST = 'REQUEST_SWAP';
export const SWAP_RESPONSE = 'SWAP_RESPONSE';

/**
 * Refund actions
 */
export const COMPLETE_REFUND = 'COMPLETE_REFUND';
export const SET_REFUND_FILE = 'SET_REFUND_FILE';
export const SET_REFUND_TXHASH = 'SET_REFUND_TXHASH';
export const SET_REFUND_DESTINATION = 'SET_REFUND_DESTINATION';
export const SET_REFUND_TRANSACTION = 'SET_REFUND_TRANSACTION';
export const SET_REFUND_TRANSACTION_HASH = 'SET_REFUND_TRANSACTION_HASH';
export const REFUND_REQUEST = 'REFUND_REQUEST';
export const REFUND_RESPONSE = 'REFUND_RESPONSE';
